build:
  commands:
    # Update packages
    - apt-get update

    # Install system libraries needed by WeasyPrint
    - apt-get install -y libcairo2 libcairo2-dev libpango-1.0-0 libpango1.0-dev libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-dev libffi-dev shared-mime-info

    # Install Python dependencies
    - pip install -r requirements.txt
